import { useState, useEffect } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { Button } from "../components/ui/button";
import { Alert, AlertDescription } from "../components/ui/alert";
import { Captcha } from "../components/Captcha";
import { CheckCircle2, AlertCircle, Eye, EyeOff } from "lucide-react";
import logo from "../../imports/1000109381-1.png";
import { usePlatform } from "../contexts/PlatformContext";
import { useSettings } from "../contexts/SettingsContext";
import { userProfileService } from "../services/userProfileService";
import { registerWithBackend } from "../services/backendAuthService";

export function Register() {
  const navigate = useNavigate();
  const { branding } = usePlatform();
  const { t } = useSettings();
  const { referralCode: urlReferralCode } = useParams();
  const [searchParams] = useSearchParams();

  // Read referral code from ?ref= query param (BZR prefix) or legacy path param
  const queryRef  = searchParams.get("ref")  || "";
  // Read affiliate code from ?aff= query param (BZA prefix)
  const queryAff  = searchParams.get("aff")  || "";

  // Determine initial referral code: query param takes priority over path param
  const initialRefCode = queryRef || urlReferralCode || "";

  const [formData, setFormData] = useState({
    fullName: "",
    username: "",
    email: "",
    password: "",
    confirmPassword: "",
    referralCode:  initialRefCode,
    affiliateCode: queryAff,
  });
  const [error, setError] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [isCaptchaVerified, setIsCaptchaVerified] = useState(false);

  useEffect(() => {
    setFormData(prev => ({
      ...prev,
      referralCode:  queryRef || urlReferralCode || prev.referralCode,
      affiliateCode: queryAff || prev.affiliateCode,
    }));
  }, [queryRef, queryAff, urlReferralCode]);

  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");

    if (!isCaptchaVerified) {
      setError("Please complete the CAPTCHA verification");
      return;
    }
    if (isSubmitting) return;
    setIsSubmitting(true);

    if (formData.password !== formData.confirmPassword) {
      setError("Passwords do not match");
      return;
    }

    if (formData.password.length < 8) {
      setError("Password must be at least 8 characters");
      return;
    }

    const newUser = {
      id: "user_" + Math.random().toString(36).substr(2, 9),
      fullName: formData.fullName,
      email: formData.email,
      username: formData.username,
      // Codes are generated by backend; this is a placeholder for local identity context
      referralCode: "",
      affiliateCode: "",
      uplineId: formData.referralCode || formData.affiliateCode || null,
      createdAt: new Date().toISOString(),
      currentLevel: 0,
      isActivated: false,
    };

    localStorage.setItem("bitzimiUser", JSON.stringify(newUser));
    userProfileService.createProfile(formData.fullName, formData.email, formData.username);

    // Register with backend — atomically creates user, both codes (BZR+BZA), wallets, and referral record.
    try {
      await registerWithBackend(
        formData.email,
        formData.password,
        formData.username,
        formData.fullName      || undefined,
        formData.referralCode  || undefined,
        formData.affiliateCode || undefined,
      );
    } catch { /* ignore — local identity is already set */ }

    setIsSubmitting(false);
    // Backend sends a verification email; direct user to the verify-email page
    navigate("/verify-email");
  };

  // When backend has disabled registration, show a closed-registration screen
  if (!branding.registrationEnabled) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 flex items-center justify-center p-4">
        <Card className="w-full max-w-md bg-gray-800/50 backdrop-blur-lg border-gray-700/80 shadow-2xl">
          <CardContent className="pt-10 pb-8 text-center space-y-4">
            <img src={branding.logoUrl || logo} alt={branding.name} className="h-9 mx-auto" />
            <div>
              <h2 className="text-xl font-semibold text-white mt-4">Registrations Closed</h2>
              <p className="text-sm text-gray-400 mt-2">New account registrations are temporarily unavailable. Please check back later.</p>
            </div>
            <Link to="/login" className="inline-block text-sm text-purple-400 hover:text-purple-300 transition-colors">
              Sign in to an existing account →
            </Link>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 flex items-center justify-center p-4 py-8">
      <Card className="w-full max-w-md bg-gray-800/50 backdrop-blur-lg border-gray-700/80 shadow-2xl">
        <CardHeader className="space-y-0.5 pb-3">
          <div className="text-center mb-2">
            <img src={branding.logoUrl || logo} alt={branding.name} className="h-9 mx-auto mb-1.5" />
            <p className="text-xs text-purple-400/90">Play, Earn & Compete Securely</p>
          </div>
          <CardTitle className="text-xl text-white">{t("auth.register.title", "Create an account")}</CardTitle>
          <CardDescription className="text-gray-400 text-sm">
            {t("auth.register.subtitle", "Join and start earning today")}
          </CardDescription>
        </CardHeader>
        <CardContent className="pt-0">
          {(formData.referralCode || formData.affiliateCode) && (
            <Alert className="mb-3 py-2 border-green-500/50 bg-green-950/30">
              <CheckCircle2 className="h-3.5 w-3.5 text-green-400" />
              <AlertDescription className="text-green-300 text-xs">
                {formData.affiliateCode
                  ? <>Joining via affiliate: <strong>{formData.affiliateCode}</strong></>
                  : <>Joining with referral code: <strong>{formData.referralCode}</strong></>
                }
              </AlertDescription>
            </Alert>
          )}

          {error && (
            <Alert variant="destructive" className="mb-3 py-2 border-red-500/50 bg-red-950/30">
              <AlertCircle className="h-3.5 w-3.5" />
              <AlertDescription className="text-xs">{error}</AlertDescription>
            </Alert>
          )}

          <form onSubmit={handleSubmit} className="space-y-3">
            {/* Name and Username - Two columns on wider screens */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label htmlFor="fullName" className="text-gray-200 text-sm">{t("auth.register.name", "Full Name")}</Label>
                <Input
                  id="fullName"
                  placeholder="John Doe"
                  value={formData.fullName}
                  onChange={(e) => setFormData({ ...formData, fullName: e.target.value })}
                  className="h-10 bg-gray-900/40 border-gray-600/60 focus:border-purple-500/60 focus:ring-purple-500/20 focus:ring-2 transition-all"
                  required
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="username" className="text-gray-200 text-sm">Username</Label>
                <Input
                  id="username"
                  placeholder="johndoe"
                  value={formData.username}
                  onChange={(e) => setFormData({ ...formData, username: e.target.value })}
                  className="h-10 bg-gray-900/40 border-gray-600/60 focus:border-purple-500/60 focus:ring-purple-500/20 focus:ring-2 transition-all"
                  required
                />
              </div>
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="email" className="text-gray-200 text-sm">{t("auth.register.email", "Email")}</Label>
              <Input
                id="email"
                type="email"
                placeholder="you@example.com"
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                className="h-10 bg-gray-900/40 border-gray-600/60 focus:border-purple-500/60 focus:ring-purple-500/20 focus:ring-2 transition-all"
                required
              />
            </div>

            {/* Password fields */}
            <div className="space-y-1.5">
              <Label htmlFor="password" className="text-gray-200 text-sm">Password <span className="text-xs text-gray-500 font-normal">(min. 8 characters)</span></Label>
              <div className="relative">
                <Input
                  id="password"
                  type={showPassword ? "text" : "password"}
                  placeholder="••••••••"
                  value={formData.password}
                  onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                  className="h-10 pr-10 bg-gray-900/40 border-gray-600/60 focus:border-purple-500/60 focus:ring-purple-500/20 focus:ring-2 transition-all"
                  required
                />
                <button
                  type="button"
                  tabIndex={-1}
                  onClick={() => setShowPassword(v => !v)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-200 transition-colors"
                  aria-label={showPassword ? "Hide password" : "Show password"}
                >
                  {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="confirmPassword" className="text-gray-200 text-sm">Confirm Password</Label>
              <div className="relative">
                <Input
                  id="confirmPassword"
                  type={showConfirmPassword ? "text" : "password"}
                  placeholder="••••••••"
                  value={formData.confirmPassword}
                  onChange={(e) => setFormData({ ...formData, confirmPassword: e.target.value })}
                  className="h-10 pr-10 bg-gray-900/40 border-gray-600/60 focus:border-purple-500/60 focus:ring-purple-500/20 focus:ring-2 transition-all"
                  required
                />
                <button
                  type="button"
                  tabIndex={-1}
                  onClick={() => setShowConfirmPassword(v => !v)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-200 transition-colors"
                  aria-label={showConfirmPassword ? "Hide password" : "Show password"}
                >
                  {showConfirmPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>
            </div>

            {/* Referral Code */}
            <div className="space-y-1.5">
              <Label htmlFor="referralCode" className="text-gray-200 text-sm">Referral Code <span className="text-xs text-gray-500 font-normal">(optional)</span></Label>
              <Input
                id="referralCode"
                placeholder="BZ123456"
                value={formData.referralCode}
                onChange={(e) => setFormData({ ...formData, referralCode: e.target.value })}
                className="h-10 font-mono bg-gray-900/40 border-gray-600/60 focus:border-purple-500/60 focus:ring-purple-500/20 focus:ring-2 transition-all"
              />
            </div>

            <Captcha onVerify={setIsCaptchaVerified} />

            <Button
              type="submit"
              className="w-full h-10 bg-gradient-to-r from-purple-600 to-purple-700 hover:from-purple-700 hover:to-purple-800 shadow-lg shadow-purple-900/40 transition-all"
              disabled={!isCaptchaVerified || isSubmitting}
            >
              {isSubmitting ? t("common.loading", "Creating Account…") : t("auth.register.submit", "Create Account")}
            </Button>
          </form>

          <div className="mt-4 text-center text-sm">
            <span className="text-gray-400">{t("auth.register.has_account", "Already have an account?")} </span>
            <Link to="/login" className="text-purple-400 hover:text-purple-300 font-medium transition-colors">
              {t("auth.register.signin", "Sign in")}
            </Link>
          </div>

          <div className="mt-2 text-center text-sm">
            <Link to="/" className="text-gray-500 hover:text-gray-400 transition-colors">
              ← Back to Home
            </Link>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
