import { useEffect, useMemo, useRef, useState } from "react";
import { useSettings } from "../contexts/SettingsContext";
import { ArrowLeft, Info, Sparkles, Trophy, TrendingUp, Users, Shield } from "lucide-react";
import { Card, CardContent } from "../components/ui/card";
import { PlayerAvatar } from "../components/PlayerAvatar";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { FairnessModal } from "../components/FairnessModal";

type Phase = "waiting" | "countdown" | "locked" | "spinning" | "result" | "completed";
export type SpinPlayer = { userId:string; username:string; index:number; avatar?:string|null; betAmount:number; color:string; segmentStart:number; segmentEnd:number; probability:number };
export type SpinWinner = { roundNumber:number; winnerId:string|null; winnerUsername:string|null; winnerPayout:number; timestamp:string; avatar?:string|null };
export type SpinState = { lobbyId:string; roundId:string; roundNumber:number; phase:Phase; playerCount:number; maxPlayers:number; minBet:number; maxBet:number; totalPool:number; timeRemaining:number|null; winnerId:string|null; winnerUsername:string|null; winnerPayout:number|null; canJoin:boolean; players:SpinPlayer[]; myBet:{inRound:boolean;amount:number|null}|null; recentWinners:SpinWinner[]; verificationId?:string|null; serverSeedHash?:string|null };
type History = { id?:string; roundNumber:number; betAmount:number; won:boolean|null; payout:number; timestamp:number };
type Props = { lobbyState:SpinState; selectedLobby:string; betAmount:string; setBetAmount:(v:string)=>void; joining:boolean; onJoin:()=>void; onBack:()=>void; balances:{game:number}; identity:{userId:string;username:string;avatar?:string|null}; userHistory:History[] };

const API_BASE = (import.meta as any).env?.VITE_API_URL as string | undefined;
const QUICK:Record<string,number[]>={A:[1,5,15],B:[21,30,40],C:[51,75,95],D:[121,230,375]};

function avatarValue(player: SpinPlayer) { return player.avatar || player.username?.charAt(0)?.toUpperCase() || "?"; }
function isImageAvatar(value:string) { return value.startsWith("data:image") || value.startsWith("http://") || value.startsWith("https://") || value.startsWith("blob:"); }

export default function SpinBattleGameplay({lobbyState,selectedLobby,betAmount,setBetAmount,joining,onJoin,onBack,balances,identity,userHistory}:Props){
 const {formatCurrency,formatCurrencyNoDecimals,currency,convertFromUSD,needsSmallFont}=useSettings();
 const [rotation,setRotation]=useState(0); const [animating,setAnimating]=useState(false); const [presentation,setPresentation]=useState<"normal"|"spinning"|"winner"|"popup">("normal"); const [underPointer,setUnderPointer]=useState<SpinPlayer|null>(null); const [activeTab,setActiveTab]=useState<"winners"|"history">("winners"); const [rules,setRules]=useState(false); const [fairness,setFairness]=useState(false); const [serverHistory,setServerHistory]=useState<History[]>([]);
 const wheelRef=useRef<HTMLDivElement|null>(null); const prevRound=useRef<number|null>(null); const prevPhase=useRef<Phase|null>(null); const raf=useRef<number|null>(null); const popupTimer=useRef<ReturnType<typeof setTimeout>|null>(null); const winnerTimer=useRef<ReturnType<typeof setTimeout>|null>(null); const historyKeyRef=useRef("");
 const inRound=!!lobbyState.myBet?.inRound; const locked=!lobbyState.canJoin||["locked","spinning","result"].includes(lobbyState.phase); const potentialWin=Math.floor(lobbyState.totalPool*.9); const winner=useMemo(()=>lobbyState.players.find(p=>p.userId===lobbyState.winnerId)||null,[lobbyState.players,lobbyState.winnerId]);

 const loadHistory=async()=>{if(!API_BASE)return;const token=localStorage.getItem("bitzimi_access_token");if(!token)return;try{const res=await fetch(`${API_BASE}/api/v1/games/history?gameType=spin_battle&limit=50`,{headers:{Authorization:`Bearer ${token}`}});if(!res.ok)return;const json=await res.json();const items=Array.isArray(json?.data?.items)?json.data.items:[];setServerHistory(items.map((b:any)=>({id:b.id,roundNumber:Number(b.roundNumber),betAmount:Number(b.amount),won:b.outcome==="win"?true:b.outcome==="loss"?false:null,payout:Number(b.payout??0),timestamp:new Date(b.placedAt).getTime()})));}catch{}};
 useEffect(()=>{loadHistory();},[selectedLobby]);
 useEffect(()=>{const key=`${lobbyState.roundId}:${lobbyState.phase}:${lobbyState.myBet?.inRound?1:0}`;if(historyKeyRef.current!==key){historyKeyRef.current=key;loadHistory();}},[lobbyState.roundId,lobbyState.phase,lobbyState.myBet?.inRound]);
 useEffect(()=>{const timer=setInterval(loadHistory,3000);return()=>clearInterval(timer);},[selectedLobby]);

 useEffect(()=>{if(prevRound.current!==null&&prevRound.current!==lobbyState.roundNumber){setRotation(0);setPresentation("normal");setAnimating(false);setUnderPointer(null);}prevRound.current=lobbyState.roundNumber;},[lobbyState.roundNumber]);
 useEffect(()=>{const prev=prevPhase.current;prevPhase.current=lobbyState.phase;if(popupTimer.current)clearTimeout(popupTimer.current);if(winnerTimer.current)clearTimeout(winnerTimer.current);
   if(lobbyState.phase==="spinning"&&prev!=="spinning"){setPresentation("spinning");setAnimating(true);requestAnimationFrame(()=>setRotation(r=>r+7*360+270));}
   if(lobbyState.phase==="result"&&prev!=="result"&&winner){setPresentation("winner");setAnimating(true);const center=(winner.segmentStart+winner.segmentEnd)/2;requestAnimationFrame(()=>setRotation(current=>{const currentMod=((current%360)+360)%360;const desired=(360-center+360)%360;const delta=((desired-currentMod)+360)%360;return current+360+delta;}));popupTimer.current=setTimeout(()=>setPresentation("popup"),4000);winnerTimer.current=setTimeout(()=>setAnimating(false),1200);loadHistory();}
   if(lobbyState.phase==="waiting"&&prev==="result")setPresentation("normal");
   return()=>{if(popupTimer.current)clearTimeout(popupTimer.current);if(winnerTimer.current)clearTimeout(winnerTimer.current);};
 },[lobbyState.phase,lobbyState.roundNumber,winner]);

 useEffect(()=>{if(!wheelRef.current||lobbyState.phase!=="spinning"||!lobbyState.players.length){setUnderPointer(null);return;}const tick=()=>{const el=wheelRef.current;if(!el)return;const transform=getComputedStyle(el).transform;let deg=0;if(transform&&transform!=="none"){const match=transform.match(/^matrix\(([^)]+)\)$/);if(match){const values=match[1].split(",").map(Number);deg=Math.atan2(values[1],values[0])*180/Math.PI;if(deg<0)deg+=360;}}const angle=(360-deg)%360;setUnderPointer(lobbyState.players.find(p=>angle>=p.segmentStart&&angle<p.segmentEnd)||null);raf.current=requestAnimationFrame(tick);};tick();return()=>{if(raf.current)cancelAnimationFrame(raf.current);};},[lobbyState.phase,lobbyState.players,rotation]);

 const wheel=()=>{const ps=lobbyState.players;if(!ps.length)return <div className="relative w-full aspect-square max-w-[400px] mx-auto"><div className="absolute inset-0 rounded-full bg-gradient-to-br from-gray-200 to-gray-300 dark:from-gray-800/50 dark:to-gray-900/50 border border-gray-300 dark:border-gray-700/50 flex items-center justify-center shadow-2xl"><div className="text-center"><Sparkles className="h-12 w-12 text-blue-500 dark:text-blue-400 mx-auto mb-3 animate-pulse"/><p className="text-gray-600 dark:text-gray-400 text-sm font-medium">Waiting for players</p></div></div></div>;
   return <div className="relative w-full aspect-square max-w-[400px] mx-auto"><div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-4 z-20"><div className="w-0 h-0 border-l-[20px] border-l-transparent border-r-[20px] border-r-transparent border-t-[30px] border-t-gray-800 dark:border-t-white drop-shadow-lg"/></div>
   <div ref={wheelRef} className="absolute inset-0 rounded-full overflow-hidden shadow-2xl border-4 border-gray-300 dark:border-gray-700/50" style={{transform:`rotate(${rotation}deg)`,transition:lobbyState.phase==="result"?"transform 1.2s cubic-bezier(0.17,0.67,0.12,0.99)":animating?"transform 8s cubic-bezier(0.17,0.67,0.12,0.99)":"none"}}>
    <svg viewBox="0 0 200 200" className="w-full h-full">{ps.map(p=>{const s=p.segmentStart*Math.PI/180-Math.PI/2,e=p.segmentEnd*Math.PI/180-Math.PI/2,arc=p.segmentEnd-p.segmentStart>180?1:0,x1=100+100*Math.cos(s),y1=100+100*Math.sin(s),x2=100+100*Math.cos(e),y2=100+100*Math.sin(e),c=((p.segmentStart+p.segmentEnd)/2)*Math.PI/180-Math.PI/2;const iconRadius=58,ax=100+iconRadius*Math.cos(c),ay=100+iconRadius*Math.sin(c),avatar=avatarValue(p);return <g key={p.userId}><path d={`M 100 100 L ${x1} ${y1} A 100 100 0 ${arc} 1 ${x2} ${y2} Z`} fill={p.color} stroke="white" strokeWidth="2"/><g transform={`translate(${ax-10},${ay-10})`}><circle cx="10" cy="10" r="10" fill="rgba(0,0,0,.25)" stroke="white" strokeWidth="1.5"/>{isImageAvatar(avatar)?<image href={avatar} x="1" y="1" width="18" height="18" preserveAspectRatio="xMidYMid slice"/>:<text x="10" y="10" fontSize="10" fontWeight="700" textAnchor="middle" dominantBaseline="central" fill="white">{avatar}</text>}</g></g>})}</svg>
   </div>
   <div className="absolute inset-0 flex items-center justify-center pointer-events-none"><div className="w-36 h-36 rounded-full bg-white dark:bg-gradient-to-br dark:from-gray-900 dark:via-black dark:to-gray-900 border-4 border-gray-300 dark:border-gray-700/50 flex items-center justify-center shadow-2xl">
     {(lobbyState.phase==="countdown"||lobbyState.phase==="locked")&&<p className={`text-5xl font-bold tabular-nums ${(lobbyState.timeRemaining??0)<=5?"text-red-500 animate-pulse":"text-gray-900 dark:text-white"}`}>{lobbyState.timeRemaining??0}</p>}
     {lobbyState.phase==="spinning"&&<div className="relative w-20 h-20 bg-gradient-to-br from-red-500 to-pink-500 rounded-full flex items-center justify-center shadow-lg"><div className="absolute inset-0 bg-red-500 rounded-full animate-ping opacity-50"/><div className="relative flex flex-col items-center justify-center gap-1"><div className="w-3 h-3 bg-white rounded-full"/><p className="text-white text-xs font-bold">LIVE</p></div></div>}
     {(lobbyState.phase==="result"||presentation==="winner"||presentation==="popup")&&winner&&<div className="flex flex-col items-center gap-1 p-2"><div className="w-10 h-10 rounded-full overflow-hidden flex items-center justify-center"><PlayerAvatar avatar={avatarValue(winner)}/></div><p className="text-gray-900 dark:text-white text-xs font-bold text-center max-w-[100px] truncate">{winner.username}</p><p className="text-yellow-500 text-xs font-bold animate-pulse">WINS!</p></div>}
   </div></div></div>;
 };
 const q=QUICK[selectedLobby]||[lobbyState.minBet,Math.round((lobbyState.minBet+lobbyState.maxBet)/2),lobbyState.maxBet];
 const history=serverHistory.length?serverHistory:userHistory;
 return <div className="max-w-7xl mx-auto space-y-6 pb-8"><div className="space-y-3"><div className="flex items-center"><Button variant="ghost" size="sm" onClick={onBack} className="hover:bg-gray-200 dark:hover:bg-gray-800 text-gray-600 dark:text-gray-400 px-3 -ml-3"><ArrowLeft className="h-4 w-4 mr-2"/><span className="text-sm font-medium">Back to Lobby</span></Button></div><div className="flex items-center justify-between gap-4"><div className="flex items-baseline gap-[6px]"><h1 className="text-xl font-bold text-gray-900 dark:text-white whitespace-nowrap">Spin Battle</h1><span className="text-sm text-gray-500 whitespace-nowrap">- Lobby {selectedLobby}</span></div><div className="flex items-center gap-2"><Button variant="outline" size="sm" onClick={()=>setFairness(true)}><Shield className="h-3.5 w-3.5 mr-1.5"/>Verify Fairness</Button><Button variant="outline" size="sm" onClick={()=>setRules(true)} className="px-4"><Info className="h-4 w-4 mr-2"/>Rules</Button></div></div><div className="flex items-center gap-2"><p className="text-sm text-gray-500">Round #{lobbyState.roundNumber}</p><div className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-red-500/10"><div className="relative"><div className="w-1.5 h-1.5 bg-red-500 rounded-full"/><div className="absolute inset-0 w-1.5 h-1.5 bg-red-500 rounded-full animate-ping opacity-75"/></div><span className="text-xs font-semibold text-red-500">Live</span></div></div></div>
 <div className="grid lg:grid-cols-3 gap-6"><div className="lg:col-span-2 space-y-6"><div className="grid grid-cols-3 gap-1"><Card><CardContent className="p-5 text-center"><TrendingUp className="h-5 w-5 text-blue-500 mx-auto mb-2"/><p className="text-xs text-gray-600 dark:text-gray-400 mb-1">Total Pool</p><p className="font-bold text-gray-900 dark:text-white text-[13px] sm:text-lg">{formatCurrency(lobbyState.totalPool)}</p></CardContent></Card><Card><CardContent className="p-5 text-center"><Users className="h-5 w-5 text-green-500 mx-auto mb-2"/><p className="text-xs text-gray-600 dark:text-gray-400 mb-1">Players</p><p className="text-2xl font-bold text-gray-900 dark:text-white">{lobbyState.playerCount}</p></CardContent></Card><Card><CardContent className="p-5 text-center"><Sparkles className="h-5 w-5 text-yellow-500 mx-auto mb-2"/><p className="text-xs text-gray-600 dark:text-gray-400 mb-1">Winner Gets</p><p className="font-bold text-gray-900 dark:text-white text-[13px] sm:text-lg">{formatCurrency(lobbyState.winnerPayout??potentialWin)}</p></CardContent></Card></div>{underPointer&&lobbyState.phase==="spinning"&&<div className="text-center"><p className="text-lg font-bold text-gray-900 dark:text-white">{underPointer.username}</p></div>}<Card className="bg-white dark:bg-gradient-to-br dark:from-gray-900/90 dark:to-gray-800/90 border-gray-200 dark:border-gray-700/50 shadow-2xl"><CardContent className="p-8 space-y-4">{wheel()}{(lobbyState.phase==="locked"||(lobbyState.phase==="countdown"&&(lobbyState.timeRemaining??99)<=5))&&<div className="text-center"><p className="text-lg font-bold text-red-500 animate-pulse">⛔ NO MORE BETS ⛔</p></div>}</CardContent></Card></div>
 <div className="space-y-6"><Card><CardContent className="p-6 space-y-4"><div><label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">Place Your Bet ({currency.symbol}{Math.floor(convertFromUSD(lobbyState.minBet)).toLocaleString()}-{currency.symbol}{Math.floor(convertFromUSD(lobbyState.maxBet)).toLocaleString()})</label><Input type="number" value={betAmount} onChange={e=>setBetAmount(e.target.value)} disabled={inRound||locked} placeholder="Enter amount" className="h-14 bg-gray-100 dark:bg-gray-800/50 text-lg"/><div className="grid grid-cols-4 gap-2 mt-3">{q.map(v=><Button key={v} size="sm" variant="outline" disabled={inRound||locked} onClick={()=>setBetAmount(Math.floor(convertFromUSD(v)).toString())} className={needsSmallFont()?"text-xs":""}>{currency.symbol}{Math.floor(convertFromUSD(v)).toLocaleString()}</Button>)}<Button size="sm" variant="outline" disabled={inRound||locked} onClick={()=>setBetAmount(Math.floor(convertFromUSD(lobbyState.maxBet)).toString())} className={needsSmallFont()?"text-xs":""}>MAX</Button></div><div className="flex justify-between mt-3"><p className="text-xs text-gray-600 dark:text-gray-500">Game Wallet Balance</p><p className="text-sm font-semibold text-gray-700 dark:text-gray-300">{formatCurrency(balances.game)}</p></div></div><Button className="w-full h-14 bg-gradient-to-r from-blue-500 to-purple-500 hover:from-blue-600 hover:to-purple-600 text-white font-bold text-lg shadow-lg disabled:opacity-50" onClick={onJoin} disabled={inRound||locked||joining}>{joining?"Joining...":inRound?"✓ Joined Round":locked?"Betting Closed":"Join Round"}</Button></CardContent></Card>
 <Card><CardContent className="p-6"><h3 className="font-semibold text-gray-900 dark:text-white mb-4 flex items-center gap-2"><Users className="h-5 w-5 text-blue-500"/>Current Players ({lobbyState.playerCount})</h3><div className="space-y-3 max-h-[300px] overflow-y-auto pr-2">{lobbyState.players.length?lobbyState.players.map(p=><div key={p.userId} className="flex items-center justify-between p-3 rounded-lg bg-gray-50 dark:bg-gray-800/30"><div className="flex items-center gap-3"><div className="w-3 h-3 rounded-full" style={{backgroundColor:p.color}}/><div className="w-10 h-10 rounded-full border-2 flex items-center justify-center text-2xl overflow-hidden" style={{borderColor:p.color}}><PlayerAvatar avatar={avatarValue(p)}/></div><div><p className="text-sm font-semibold text-gray-900 dark:text-white">{p.username}{p.userId===identity.userId?" (you)":""}</p><p className="text-xs text-gray-600 dark:text-gray-400">{p.probability.toFixed(1)}% chance</p></div></div><p className="text-sm font-bold text-gray-900 dark:text-white">{formatCurrency(p.betAmount)}</p></div>):<p className="text-sm text-gray-600 text-center py-8">No players yet</p>}</div></CardContent></Card>
 <Card><CardContent className="p-6"><div className="flex gap-4 border-b border-gray-200 dark:border-gray-700 mb-4"><button onClick={()=>setActiveTab("winners")} className={`pb-3 px-1 text-sm font-semibold ${activeTab==="winners"?"text-gray-900 dark:text-white border-b-2 border-blue-500":"text-gray-500"}`}>Recent Winners</button><button onClick={()=>setActiveTab("history")} className={`pb-3 px-1 text-sm font-semibold ${activeTab==="history"?"text-gray-900 dark:text-white border-b-2 border-blue-500":"text-gray-500"}`}>Your History</button></div><div className="space-y-3 max-h-[280px] overflow-y-auto pr-2">{activeTab==="winners"?(lobbyState.recentWinners.length?lobbyState.recentWinners.map((w,i)=><div key={`${w.roundNumber}-${i}`} className="flex items-center gap-3 p-3 rounded-lg bg-gray-50 dark:bg-gray-800/30"><div className="w-10 h-10 rounded-full border-2 border-yellow-500/50 flex items-center justify-center overflow-hidden"><PlayerAvatar avatar={w.winnerId===identity.userId?identity.avatar||avatarValue({userId:w.winnerId??"",username:w.winnerUsername??"?",index:0,avatar:w.avatar,betAmount:0,color:"",segmentStart:0,segmentEnd:0,probability:0}):avatarValue({userId:w.winnerId??"",username:w.winnerUsername??"?",index:0,avatar:w.avatar,betAmount:0,color:"",segmentStart:0,segmentEnd:0,probability:0})}/></div><div className="flex-1"><p className="text-xs text-gray-600 dark:text-gray-400">Round #{w.roundNumber}</p><p className="text-sm font-semibold text-gray-900 dark:text-white">{w.winnerUsername??"Unknown"}</p></div><p className="text-sm font-bold text-yellow-600 dark:text-yellow-400">{formatCurrency(w.winnerPayout)}</p></div>):<p className="text-sm text-gray-600 text-center py-6">No winners yet</p>):(history.length?history.map((h,i)=><div key={h.id??`${h.roundNumber}-${i}`} className="flex items-center justify-between p-3 rounded-lg bg-gray-50 dark:bg-gray-800/30"><div><p className="text-xs text-gray-600 dark:text-gray-400">Round #{h.roundNumber}</p><p className="text-sm text-gray-900 dark:text-white">Bet: {formatCurrency(h.betAmount)}</p></div><div className="text-right">{h.won===null?<p className="text-xs font-bold text-blue-500">PENDING</p>:<><p className={`text-xs font-bold ${h.won?"text-green-500":"text-red-500"}`}>{h.won?"WIN":"LOSS"}</p>{h.won&&<p className="text-sm font-bold text-green-500">+{formatCurrency(h.payout)}</p>}</>}</div></div>):<p className="text-sm text-gray-600 text-center py-6">No bets placed yet</p>)}</div></CardContent></Card></div></div>
 {rules&&<div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 p-4" onClick={()=>setRules(false)}><Card className="max-w-lg w-full max-h-[70vh] overflow-y-auto bg-white dark:bg-gray-900" onClick={e=>e.stopPropagation()}><CardContent className="p-6 sm:p-10 space-y-4"><div className="flex items-center justify-between"><h2 className="text-xl sm:text-3xl font-bold text-gray-900 dark:text-white">How to Play</h2><Button variant="ghost" size="sm" onClick={()=>setRules(false)} className="text-2xl">×</Button></div><div className="space-y-3 text-sm text-gray-700 dark:text-gray-300">{[["Join the Round","Enter your bet amount from the Game Wallet and join the current round."],["Game Runs 24/7","The game continues even when you're not watching. Join anytime during the countdown!"],["Win Probability","Your wheel segment is proportional to your bet amount. Bigger bets give a larger segment."],["Winner Selection","The server selects the winner. The wheel only visualizes the authoritative result."],["Payout","Winner receives the pool minus the platform fee."]].map(([t,b],i)=><div className="flex gap-3" key={i}><div className="w-6 h-6 rounded-full bg-blue-500/20 flex items-center justify-center text-blue-500 font-bold text-xs">{i+1}</div><div><p className="font-semibold text-gray-900 dark:text-white">{t}</p><p>{b}</p></div></div>)}</div><Button className="w-full" onClick={()=>setRules(false)}>Got it!</Button></CardContent></Card></div>}
 <FairnessModal isOpen={fairness} onClose={()=>setFairness(false)} gameType="spin_battle" verificationId={lobbyState.verificationId} roundNumber={lobbyState.roundNumber} serverSeedHash={lobbyState.serverSeedHash??undefined}/>
 {presentation==="popup"&&winner&&<div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50 p-4 animate-in fade-in duration-500"><Card className="w-full max-w-[360px] sm:max-w-xl bg-gradient-to-br from-yellow-900/90 via-orange-900/90 to-red-900/90 border-yellow-500/50 shadow-2xl"><CardContent className="p-6 sm:p-12"><div className="text-center space-y-5 sm:space-y-8"><Trophy className="h-16 w-16 sm:h-24 sm:w-24 text-yellow-400 animate-bounce mx-auto"/><div><p className="text-xs sm:text-lg text-yellow-300 font-semibold">Round #{lobbyState.roundNumber} Winner</p><p className="text-3xl sm:text-6xl font-bold text-white">{winner.username}</p></div><div className="flex justify-center"><div className="w-24 h-24 sm:w-48 sm:h-48 rounded-full border-4 sm:border-8 border-yellow-400 shadow-2xl bg-black/20 flex items-center justify-center overflow-hidden"><PlayerAvatar avatar={avatarValue(winner)}/></div></div><div className="bg-black/30 rounded-lg p-4 sm:p-10"><p className="text-xs sm:text-lg text-gray-300 mb-2">Prize Won</p><p className="text-2xl sm:text-6xl font-bold text-yellow-400">{formatCurrency(lobbyState.winnerPayout??0)}</p></div></div></CardContent></Card></div>}
 </div>;
}
