import { createContext, useContext, useState, useEffect, useCallback, type ReactNode } from "react";
const API_BASE = (import.meta as any).env?.VITE_API_URL as string | undefined ?? "";
function getToken() { return localStorage.getItem("bitzimi_access_token"); }
export type Currency = { code:string; name:string; symbol:string; rate:number };
export type Language = { code:string; name:string; nativeName?:string; flag?:string|null; direction?:"ltr"|"rtl"; isDefault?:boolean; isEnabled?:boolean; sortOrder?:number };
export const CURRENCIES: Currency[] = [
 {code:"USD",name:"US Dollar",symbol:"$",rate:1},{code:"EUR",name:"Euro",symbol:"€",rate:0.92},{code:"GBP",name:"British Pound",symbol:"£",rate:0.79},{code:"NGN",name:"Nigerian Naira",symbol:"₦",rate:1650},{code:"CNY",name:"Chinese Yuan",symbol:"¥",rate:7.25},{code:"INR",name:"Indian Rupee",symbol:"₹",rate:83},{code:"ZAR",name:"South African Rand",symbol:"R",rate:18.5},{code:"KES",name:"Kenyan Shilling",symbol:"KSh",rate:130},{code:"RUB",name:"Russian Ruble",symbol:"₽",rate:90},{code:"TRY",name:"Turkish Lira",symbol:"₺",rate:32}
];
const FALLBACK_LANGUAGE:Language={code:"en",name:"English",direction:"ltr"};
type Theme="light"|"dark";
type SettingsContextType={theme:Theme;setTheme:(theme:Theme)=>void;language:Language;setLanguage:(language:Language)=>void;availableLanguages:Language[];translationsLoaded:boolean;currency:Currency;setCurrency:(currency:Currency)=>void;availableCurrencies:Currency[];formatCurrency:(amount:number)=>string;formatCurrencyNoDecimals:(amount:number)=>string;convertCurrency:(amount:number)=>number;convertToUSD:(amount:number)=>number;convertFromUSD:(amount:number)=>number;needsSmallFont:()=>boolean;t:(key:string,fallback?:string)=>string};
const SettingsContext=createContext<SettingsContextType|undefined>(undefined);
export function SettingsProvider({children}:{children:ReactNode}){
 const [theme,setThemeState]=useState<Theme>(()=>{try{return(localStorage.getItem("bitzimiTheme") as Theme)||"dark"}catch{return"dark"}});
 const setTheme=useCallback((t:Theme)=>{setThemeState(t);try{localStorage.setItem("bitzimiTheme",t)}catch{};if(t==="dark")document.documentElement.classList.add("dark");else document.documentElement.classList.remove("dark")},[]);
 useEffect(()=>{if(theme==="dark")document.documentElement.classList.add("dark");else document.documentElement.classList.remove("dark")},[]);
 const [availableLanguages,setAvailableLanguages]=useState<Language[]>([FALLBACK_LANGUAGE]);const [translationBundle,setTranslationBundle]=useState<Record<string,string>>({});const [translationsLoaded,setTranslationsLoaded]=useState(false);
 const [language,setLanguageState]=useState<Language>(()=>{try{const saved=localStorage.getItem("bitzimiLanguage");return saved?JSON.parse(saved):FALLBACK_LANGUAGE}catch{return FALLBACK_LANGUAGE}});
 const fetchTranslations=useCallback(async(lang:Language)=>{if(!API_BASE){setTranslationsLoaded(true);return}try{const res=await fetch(`${API_BASE}/api/v1/translations/${lang.code}`);const json=await res.json();if(json?.data)setTranslationBundle(json.data)}catch{}finally{setTranslationsLoaded(true)}},[]);
 const setLanguage=useCallback((lang:Language)=>{
   setLanguageState(lang);try{localStorage.setItem("bitzimiLanguage",JSON.stringify(lang))}catch{}
   const dir=lang.direction==="rtl"?"rtl":"ltr";document.documentElement.setAttribute("dir",dir);document.documentElement.setAttribute("lang",lang.code);fetchTranslations(lang);
   const token=getToken();
   if(API_BASE&&token){fetch(`${API_BASE}/api/v1/users/me/preferences`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({languagePref:lang.code})}).catch(()=>{});}
 },[fetchTranslations]);
 useEffect(()=>{if(!API_BASE)return;fetch(`${API_BASE}/api/v1/languages`).then(r=>r.json()).then(json=>{const langs:Language[]=json?.data??[];if(langs.length){setAvailableLanguages(langs);setLanguageState(prev=>langs.find(l=>l.code===prev.code)??prev)}}).catch(()=>{})},[]);
 useEffect(()=>{const dir=language.direction==="rtl"?"rtl":"ltr";document.documentElement.setAttribute("dir",dir);document.documentElement.setAttribute("lang",language.code);fetchTranslations(language)},[]);
 const [currency,setCurrencyState]=useState<Currency>(()=>{try{const saved=localStorage.getItem("bitzimiCurrency");return saved?JSON.parse(saved):CURRENCIES[0]}catch{return CURRENCIES[0]}});const [availableCurrencies,setAvailableCurrencies]=useState<Currency[]>(CURRENCIES);
 const setCurrency=useCallback((c:Currency)=>{setCurrencyState(c);try{localStorage.setItem("bitzimiCurrency",JSON.stringify(c))}catch{};const token=getToken();if(API_BASE&&token)fetch(`${API_BASE}/api/v1/users/me/preferences`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({currencyPref:c.code)}).catch(()=>{})},[]);
 useEffect(()=>{if(!API_BASE)return;const hasSavedCurrency=!!localStorage.getItem("bitzimiCurrency");Promise.all([fetch(`${API_BASE}/api/v1/currencies`).then(r=>r.json()).catch(()=>null),hasSavedCurrency?null:fetch(`${API_BASE}/api/v1/currencies/default`).then(r=>r.json()).catch(()=>null)]).then(([listJson,defaultJson])=>{const list:Currency[]=((listJson?.data??[]) as any[]).map((c:any)=>({code:c.code,name:c.name??c.code,symbol:c.symbol,rate:c.rate}));if(list.length){setAvailableCurrencies(list);setCurrencyState(prev=>{if(hasSavedCurrency)return list.find(c=>c.code===prev.code)??prev;if(defaultJson?.data){const d=defaultJson.data;return{code:d.code,name:d.name??d.code,symbol:d.symbol,rate:d.rate}}return list[0]})}}).catch(()=>{})},[]);
 useEffect(()=>{const token=getToken();if(!API_BASE||!token)return;fetch(`${API_BASE}/api/v1/users/me/preferences`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json()).then(json=>{const pref=json?.data;if(!pref)return;if(pref.themePref)setTheme(pref.themePref as Theme);if(pref.languagePref){const l=availableLanguages.find(x=>x.code===pref.languagePref);if(l)setLanguage(l)}if(pref.currencyPref){const c=availableCurrencies.find(x=>x.code===pref.currencyPref);if(c)setCurrency(c)}}).catch(()=>{})},[]);
 const convertCurrency=(amount:number):number=>{if(!isFinite(amount)||!isFinite(currency.rate)||currency.rate<=0)return 0;return amount*currency.rate};const convertToUSD=(amount:number):number=>{if(!isFinite(amount)||!isFinite(currency.rate)||currency.rate<=0)return 0;return amount/currency.rate};const convertFromUSD=(amount:number):number=>{if(!isFinite(amount)||!isFinite(currency.rate)||currency.rate<=0)return 0;return amount*currency.rate};
 const formatCurrency=(amount:number):string=>{if(!isFinite(amount))return`${currency.symbol}0`;const converted=convertCurrency(amount);if(!isFinite(converted))return`${currency.symbol}0`;return`${currency.symbol}${converted.toLocaleString(undefined,{minimumFractionDigits:0,maximumFractionDigits:2})}`};
 const formatCurrencyNoDecimals=(amount:number):string=>{if(!isFinite(amount))return`${currency.symbol}0`;const converted=convertCurrency(amount);if(!isFinite(converted))return`${currency.symbol}0`;return`${currency.symbol}${converted.toLocaleString(undefined,{minimumFractionDigits:0,maximumFractionDigits:2})}`};
 const needsSmallFont=()=>currency.rate>20;const t=useCallback((key:string,fallback?:string):string=>{if(translationBundle[key])return translationBundle[key];if(translationBundle[`common.${key}`])return translationBundle[`common.${key}`];if(fallback)return fallback;return key.split(".").pop()?.replace(/_/g," ")??key},[translationBundle]);
 return <SettingsContext.Provider value={{theme,setTheme,language,setLanguage,availableLanguages,translationsLoaded,currency,setCurrency,availableCurrencies,formatCurrency,formatCurrencyNoDecimals,convertCurrency,convertToUSD,convertFromUSD,needsSmallFont,t}}>{children}</SettingsContext.Provider>;
}
export function useSettings(){const context=useContext(SettingsContext);if(!context)throw new Error("useSettings must be used within SettingsProvider");return context}
